<?php if (!defined('BASEPATH'))  exit('No direct script access allowed'); 

/*
* SHOP for PyroCMS
* 
* Copyright (c) 2013, Salvatore Bordonaro
* This file was automaticly generated by Shop CoreBasiks Library Helper..
*/

$lang['shop:dashboard:alerts']  = 'Alerts';
